---
title: "Armed Conflict Location Event"
author: "Akira Sasaki, Eduardo Acostamadiedo, Oliver Recep Çok"
date: "11/24/2017"
output: pdf_document
---

```{r setup, include=FALSE, echo=FALSE}
rm(list = ls())
library(knitr)
opts_chunk$set(message = FALSE, error = TRUE, fig.pos = 'H', tidy.opts=list(width.cutoff=65), tidy=TRUE, fig.path='figs/', cache.path='cache/graphics-', 
           fig.pos ='H', fig.align='center', fig.width = 5, fig.height = 4, fig.show = 'hold',
           cache = TRUE, par = TRUE)
```

```{r library, include=FALSE, echo=FALSE}
install.packages("shiny", repos = "https://cran.rstudio.com/")
library(shiny)
install.packages("shinydashboard", repos = "https://cran.rstudio.com/")
library(shinydashboard)
library(scales)
library(foreign) #read foreign file objects
install.packages("dplyr", repos = "https://cran.rstudio.com/")
library(dplyr) #manipulate data
install.packages("ggplot2", repos = "https://cran.rstudio.com/")
library(ggplot2) #plot results
install.packages("psych", repos = "https://cran.rstudio.com/")
library(psych) #create summary statistics
library(plyr) #tools for splitting, qpplying and combining data
library(data.table)
require(haven)
library(lubridate)
install.packages("repmis", repos = "https://cran.rstudio.com/")
library(repmis)
library(data.table)
library(magrittr)
install.packages("stargazer", repos = "https://cran.rstudio.com/")
library(stargazer)
install.packages("broom", repos = "https://cran.rstudio.com/")
library(broom)
install.packages("arm", repos = "https://cran.rstudio.com/")
library(arm)
library(readr)
library(readxl)
library(tidyverse)
library(tidyr) 
library(stringr)
library(httr) 
install.packages("twitteR", repos = "https://cran.rstudio.com/")
library(twitteR)
library(rvest) 
install.packages("streamR", repos = "https://cran.rstudio.com/")
library(streamR)
install.packages("RCurl", repos = "https://cran.rstudio.com/")
library(RCurl)
install.packages("ROAuth", repos = "https://cran.rstudio.com/")
library(ROAuth)
install.packages("stringi", repos = "https://cran.rstudio.com/")
library(stringi)
install.packages("plm", repos = "https://cran.rstudio.com/")
library(plm)
install.packages("countrycode", repos = "https://cran.rstudio.com/")
library(countrycode)
install.packages("plm", repos = "https://cran.rstudio.com/")
library(plm)
install.packages("foreign", repos = "https://cran.rstudio.com/")
library(foreign)
install.packages("sandwich", repos = "https://cran.rstudio.com/")
library(sandwich)
install.packages("lmtest", repos = "https://cran.rstudio.com/")
library(lmtest)
install.packages("ggExtra", repos = "https://cran.rstudio.com/")
library(ggExtra)

```

```{r DATA, include=FALSE, echo=FALSE}
#ACLED
ACLED <- read_csv("~/Armed-Conflict-Location-Event-Data/ACLED-Version-7-All-Africa-1997-2016_csv_dyadic-file.csv")
ACLED <- subset(ACLED, select = c("YEAR","EVENT_TYPE", "COUNTRY"))
names(ACLED)[names(ACLED) == 'COUNTRY'] <- "country"
names(ACLED)[names(ACLED) == 'YEAR'] <- 'year'
ACLED <- ACLED %>% dplyr::group_by(year, country, EVENT_TYPE) %>% dplyr::summarize(count = n())
ACLED <- apply(ACLED,2,toupper)

cat_social_conflict <- c("RIOTS/PROTESTS", "VIOLENCE AGAINST CIVILIANS")

ACLED <- ACLED %>% 
  as.data.frame()
ACLED2 <- ACLED %>% 
  dplyr::mutate(dep1 = ifelse(EVENT_TYPE %in% cat_social_conflict, "CIVILIAN INVOLVED CONFLICT", "ARMED GROUP CONFLICT" ))

ACLED2$count <- as.numeric(ACLED2$count)
ACLED2 <- ACLED2 %>% 
  ungroup() %>%
  dplyr::group_by(country, year, dep1) %>%
  dplyr::summarise(dep2 = sum(count)) %>%
  spread(dep1, dep2)
ACLED2$iso3c <- countrycode(ACLED2$country, 'country.name','iso3c', warn = T)

#GDP per capita
GDP <- read_excel("~/Armed-Conflict-Location-Event-Data/Statistical model/GDP per capita/GDP.xlsx")
GDP <- apply(GDP,2,toupper)
GDP <- as.data.frame(GDP)
GDP$Country <- recode(GDP$Country,"CONGO"="Republic of Congo")
GDP$Country <- recode(GDP$Country,"CONGO (DEMOCRATIC REPUBLIC OF THE)"="Democratic Republic of Congo")
GDP$Country <- recode(GDP$Country,"CÔTE D'IVOIRE"="Ivory Coast")
GDP$Country <- recode(GDP$Country,"TANZANIA (UNITED REPUBLIC OF)"="Tanzania")
GDP <- as.data.frame(GDP)
names(GDP)[names(GDP)== "Country"] <- "country"
names(GDP)[names(GDP)== "score"] <- "GDP"
GDP <- GDP %>% gather(key = year, value = GDP, -country)
GDP$iso3c <- countrycode(GDP$country, 'country.name','iso3c', warn = T)
  
DATA <- merge(ACLED2, GDP, by=c("year","iso3c"))

#Dependent variables natural log 
DATA$`ARMED GROUP CONFLICT` <- DATA$`ARMED GROUP CONFLICT` %>% as.numeric()
DATA$`CIVILIAN INVOLVED CONFLICT`<- DATA$`CIVILIAN INVOLVED CONFLICT` %>% as.numeric()
DATA$lnmilitary <- log(DATA$`ARMED GROUP CONFLICT`)
DATA$lnsocial <- log(DATA$`CIVILIAN INVOLVED CONFLICT`)

#facebook

#2010 Country names
url <- "https://web.archive.org/web/20101008034936/http://internetworldstats.com/africa.htm"
css <- "img+ font b"
url_parsed <- read_html(url)
country_name_2010 <- html_nodes(url_parsed, css = css) %>% html_text

#2010info
url <- "https://web.archive.org/web/20101008034936/http://internetworldstats.com/africa.htm"
css <- "tr:nth-child(9) font"
url_parsed <- read_html(url)
country_info_2010 <- html_nodes(url_parsed, css = css) %>% html_text

#2011Country names
url <- "https://web.archive.org/web/20111002190951/http://www.internetworldstats.com:80/africa.htm"
css <- "img+ font b"
url_parsed <- read_html(url)
country_name_2011 <- html_nodes(url_parsed, css = css) %>% html_text

#2011info
url <- "https://web.archive.org/web/20111002190951/http://www.internetworldstats.com:80/africa.htm"
css <- "tr:nth-child(9) font"
url_parsed <- read_html(url)
country_info_2011 <- html_nodes(url_parsed, css = css) %>% html_text

#2012Country names
url <- "https://web.archive.org/web/20121014111737/http://www.internetworldstats.com:80/africa.htm"
css <- "img+ font b"
url_parsed <- read_html(url)
country_name_2012 <- html_nodes(url_parsed, css = css) %>% html_text

#2012info
url <- "https://web.archive.org/web/20121014111737/http://www.internetworldstats.com:80/africa.htm"
css <- "tr:nth-child(9) font" 
url_parsed <- read_html(url)
country_info_2012 <- html_nodes(url_parsed, css = css) %>% html_text

#2013Country names
url <- "https://web.archive.org/web/20131015014009/http://www.internetworldstats.com/africa.htm"
css <- "font~ img+ font b"
url_parsed <- read_html(url)
country_name_2013 <- html_nodes(url_parsed, css = css) %>% html_text

#2013info
url <- "https://web.archive.org/web/20131015014009/http://www.internetworldstats.com/africa.htm"
css <- "tr:nth-child(9) font" 
url_parsed <- read_html(url)
country_info_2013 <- html_nodes(url_parsed, css = css) %>% html_text

#2014Country names
url <- "https://web.archive.org/web/20141013134528/http://www.internetworldstats.com/africa.htm"
css <- "font~ img+ font b"
url_parsed <- read_html(url)
country_name_2014 <- html_nodes(url_parsed, css = css) %>% html_text

#2014info
url <- "https://web.archive.org/web/20141013134528/http://www.internetworldstats.com/africa.htm"
css <- "tr:nth-child(9) font" 
url_parsed <- read_html(url)
country_info_2014 <- html_nodes(url_parsed, css = css) %>% html_text

#2015Country names
url <- "https://web.archive.org/web/20151020040350/http://www.internetworldstats.com:80/africa.htm"
css <- "font~ img+ font b"
url_parsed <- read_html(url)
country_name_2015 <- html_nodes(url_parsed, css = css) %>% html_text

#2015info
url <- "https://web.archive.org/web/20151020040350/http://www.internetworldstats.com:80/africa.htm"
css <- "tr:nth-child(9) font" 
url_parsed <- read_html(url)
country_info_2015 <- html_nodes(url_parsed, css = css) %>% html_text

#2016Country names
url <- "https://web.archive.org/web/20161001223626/http://www.internetworldstats.com/africa.htm"
css <- "font~ img+ font b"
url_parsed <- read_html(url)
country_name_2016 <- html_nodes(url_parsed, css = css) %>% html_text

#2016info
url <- "https://web.archive.org/web/20161001223626/http://www.internetworldstats.com/africa.htm"
css <- "tr:nth-child(9) font" 
url_parsed <- read_html(url)
country_info_2016 <- html_nodes(url_parsed, css = css) %>% html_text

n2010 <- data.frame(country_name_2010)  
i2010 <- data.frame(country_info_2010)
m2010 <- rbind(country_name_2010, country_info_2010)
m2010 <- data.frame(m2010)
m2010 <- t(m2010)
colnames(m2010) <- c("country", "data")
m2010 <- data.frame(m2010)
m2010$year="2010"

n2011 <- data.frame(country_name_2011)  
i2011 <- data.frame(country_info_2011)
m2011 <- rbind(country_name_2011, country_info_2011)
m2011 <- data.frame(m2011)
m2011 <- t(m2011)
colnames(m2011) <- c("country", "data")
m2011 <- data.frame(m2011)
m2011$year="2011"

n2012 <- data.frame(country_name_2012)  
i2012 <- data.frame(country_info_2012)
m2012 <- rbind(country_name_2012, country_info_2012)
m2012 <- data.frame(m2012)
m2012 <- t(m2012)
colnames(m2012) <- c("country", "data")
m2012 <- data.frame(m2012)
m2012$year="2012"

n2013 <- data.frame(country_name_2013)  
i2013 <- data.frame(country_info_2013)
m2013 <- rbind(country_name_2013, country_info_2013)
m2013 <- data.frame(m2013)
m2013 <- t(m2013)
colnames(m2013) <- c("country", "data")
m2013 <- data.frame(m2013)
m2013$year="2013"

n2014 <- data.frame(country_name_2014)  
i2014 <- data.frame(country_info_2014)
m2014 <- rbind(country_name_2014, country_info_2014)
m2014 <- data.frame(m2014)
m2014 <- t(m2014)
colnames(m2014) <- c("country", "data")
m2014 <- data.frame(m2014)
m2014$year="2014"

n2015 <- data.frame(country_name_2015)  
i2015 <- data.frame(country_info_2015)
m2015 <- rbind(country_name_2015, country_info_2015)
m2015 <- data.frame(m2015)
m2015 <- t(m2015)
colnames(m2015) <- c("country", "data")
m2015 <- data.frame(m2015)
m2015$year="2015"

n2016 <- data.frame(country_name_2016)  
i2016 <- data.frame(country_info_2016)
m2016 <- rbind(country_name_2016, country_info_2016)
m2016 <- data.frame(m2016)
m2016 <- t(m2016)
colnames(m2016) <- c("country", "data")
m2016 <- data.frame(m2016)
m2016$year="2016"

facebook <- rbind(m2010, m2011, m2012, m2013, m2014, m2015, m2016) 
facebook$data <- str_replace_all(facebook$data, ",", "")
facebook$subscription <- stri_extract_first_regex(facebook$data, "[0-9]+")
facebook$penetration <- str_extract(facebook$data, "((\\d+\\.*\\d*)\\%)")
facebook$penetration <- str_replace_all(facebook$penetration, "%", "")
facebook$data <- NULL
facebook$country <- gsub("EQUATORIAL\nGUINEA","EQUATORIAL GUINEA", facebook$country) 
facebook$country <-gsub("CENTRAL AFRICAN\n REPUBLIC","CENTRAL AFRICAN REPUBLIC", facebook$country) 
facebook <- data.frame(lapply(facebook, as.character), stringsAsFactors=FALSE)
facebook$iso3c <- countrycode(facebook$country, 'country.name', 
                             'iso3c', warn = T)
facebook<-data.frame(facebook)

DATA <- merge(DATA, facebook, by=c("year","iso3c"))
DATA <- subset(DATA, select = -c(country.y, country))
DATA$penetration <- as.numeric(DATA$penetration)
names(DATA)[names(DATA)== "country.x"] <- "country"

#log GDP
DATA$GDP <- as.numeric(as.character(DATA$GDP))
DATA$lnGDP <- log1p(DATA$GDP)
```

```{r 2010 civconflict, include=FALSE, echo=FALSE}

DATA[is.na(DATA)] <- 0
DATA2010 <-DATA
DATA2010 <- DATA2010[ which(DATA2010$year==2010), ]
DATA2010$GDP<-as.numeric(DATA2010$GDP) 
DATA2010$subscription<-as.numeric(DATA2010$subscription) 
DATA2010$penetration<-as.numeric(DATA2010$penetration) 
DATA2010[is.na(DATA2010)] <- 0
names(DATA2010)[names(DATA2010) == "CIVILIAN INVOLVED CONFLICT"] <- "CIVILIANINVOLVEDCONFLICT"
names(DATA2010)[names(DATA2010) == "ARMED GROUP CONFLICT"] <- "ARMEDGROUPCONFLICT"

DATA2015 <-DATA
DATA2015 <- DATA2015[ which(DATA2015$year==2015), ]
DATA2015$GDP<-as.numeric(DATA2015$GDP) 
DATA2015$subscription<-as.numeric(DATA2015$subscription) 
DATA2015$penetration<-as.numeric(DATA2015$penetration) 
DATA2015[is.na(DATA2015)] <- 0
names(DATA2015)[names(DATA2015) == "CIVILIAN INVOLVED CONFLICT"] <- "CIVILIANINVOLVEDCONFLICT"
names(DATA2015)[names(DATA2015) == "ARMED GROUP CONFLICT"] <- "ARMEDGROUPCONFLICT"

```


```{r summary statistics 2010, echo=FALSE, results='asis'}

mydata <- DATA2010
stargazer(mydata [c("ARMEDGROUPCONFLICT","CIVILIANINVOLVEDCONFLICT","GDP","subscription")],header = FALSE, float = TRUE, title="Descriptive statistics 2010", digits=1, out="html",covariate.labels = c("Armed actors events","Civilian events","GDP per cap.","% of Facebook users"))

mydata2 <- DATA2015
stargazer(mydata2 [c("ARMEDGROUPCONFLICT","CIVILIANINVOLVEDCONFLICT","GDP","subscription")], header = FALSE, float = TRUE, title="Descriptive statistics 2015", digits=1, out="html",covariate.labels = c("Armed actors events","Civilian events","GDP per cap.","% of Facebook users"))

```

```{r civil conflict plot 2010, echo=FALSE, results='asis', warning = FALSE}
options(scipen=999) 
theme_set(theme_bw())
civsoc10 <- DATA2010[DATA2010$CIVILIANINVOLVEDCONFLICT & DATA2010$subscription , ]
g <- ggplot(DATA2010, aes(subscription, CIVILIANINVOLVEDCONFLICT)) + 
  geom_count() + 
  geom_smooth(method="lm", se=F)+ 
  labs(subtitle="Facebook users vs. Civil society conflict events", 
       y="Civil soc conflict", 
       x="Facebook", 
       title="Civil Conflicts by facebook users 2010", 
       caption = "Source: ACLED, Internet Stats")+
  scale_x_log10()
plot(g)
```


```{r 2015 civilian conflict, echo=FALSE, results='asis', warning = FALSE}
options(scipen=999) 
theme_set(theme_bw())
civsoc15 <- DATA2015[DATA2015$CIVILIANINVOLVEDCONFLICT & DATA2015$subscription , ]
a <- ggplot(DATA2015, aes(subscription, CIVILIANINVOLVEDCONFLICT)) + 
  geom_count() + 
  geom_smooth(method="lm", se=F)+ 
  labs(subtitle="Facebook users vs. Civil society conflict events", 
       y="Civil soc conflict", 
       x="Facebook", 
       title="Civil Conflicts by facebook users 2015", 
       caption = "Source: ACLED, Internet Stats")+
  scale_x_log10()
plot(a)
```

```{r armed group conflict plot 2010, echo=FALSE, results='asis', warning = FALSE}
options(scipen=999) 
theme_set(theme_bw())
civsoc10 <- DATA2010[DATA2010$ARMEDGROUPCONFLICT & DATA2010$subscription , ]
b <- ggplot(DATA2010, aes(subscription, ARMEDGROUPCONFLICT)) + 
  geom_count() + 
  geom_smooth(method="lm", se=F)+ 
  labs(subtitle="Facebook users vs. Civil society conflict events", 
       y="Armed group conflict", 
       x="Facebook", 
       title="Armed Group Conflict by facebook users 2010", 
       caption = "Source: ACLED, Internet Stats")+
  scale_x_log10()
plot(b)
```

```{r armed group conflict plot 2015, echo=FALSE, results='asis', warning = FALSE}
options(scipen=999) 
theme_set(theme_bw())
civsoc10 <- DATA2015[DATA2010$ARMEDGROUPCONFLICT & DATA2015$subscription , ]
c <- ggplot(DATA2015, aes(subscription, ARMEDGROUPCONFLICT)) + 
  geom_count() + 
  geom_smooth(method="lm", se=F)+ 
  labs(subtitle="Facebook users vs. Civil society conflict events", 
       y="Armed group conflict", 
       x="Facebook", 
       title="Armed Group Conflict by facebook users 2015",
       caption = "Source: ACLED, Internet Stats")+
  scale_x_log10()
plot(c)
```

```{r regressions output, include=FALSE, echo=FALSE}
#Civilian regressions
#2010
reg10soc = lm(CIVILIANINVOLVEDCONFLICT ~ penetration + lnGDP, data= DATA2010)
m1<-coeftest(reg10soc, vcov = vcovHC(reg10soc, "HC1"))
#2015
reg15soc = lm(CIVILIANINVOLVEDCONFLICT ~ penetration + lnGDP, data= DATA2015)
m2<-coeftest(reg15soc, vcov = vcovHC(reg15soc, "HC1"))

#Armed group regressions
#2010
reg10armed = lm(ARMEDGROUPCONFLICT ~ penetration + lnGDP, data= DATA2010)
m3<-coeftest(reg10armed, vcov = vcovHC(reg10armed, "HC1"))
#2015
reg15armed = lm(ARMEDGROUPCONFLICT ~ penetration + lnGDP, data= DATA2015)
m4<-coeftest(reg15armed, vcov = vcovHC(reg15armed, "HC1"))

```

```{r actual reg output, echo=FALSE, results='asis'}
stargazer(m1, m2, 
          header = FALSE, float = TRUE,
          report = ('vc*p'),
          title            = "Civilan Conflicts",
          dep.var.labels=c("Civilian events 2010 and 2015"),
          covariate.labels=c("Facebook penetration","GDP per cap. (log)"),
          out="html")

stargazer(m3, m4, 
          header = FALSE, float = TRUE,
          report = ('vc*p'),
          title            = "Armed Group Conflicts",
          dep.var.labels=c("Armed actors events 2010 and 2015"),
          covariate.labels=c("Facebook penetration","GDP per cap. (log)"),
          out = "html")
```

```{r fixed effect regression, include=FALSE, echo=FALSE}
#see https://cran.r-project.org/web/packages/plm/vignettes/plm.pdf
fe.lnmilitary <- plm(lnmilitary ~ penetration + lnGDP, index=c("country", "year"), data=DATA, effect="twoways")
fe.lnsocial <- plm(lnsocial ~ penetration + lnGDP, index=c("country", "year"), data=DATA, effect="twoways")
``` 

```{r regression table, echo=FALSE, results='asis'}
stargazer(fe.lnmilitary, fe.lnsocial,
          header = FALSE, float = TRUE,
          report = ('vc*p'),
          title            = "Two-way Fixed Effect Regression",
          covariate.labels = c("Facebook penetration", "GDP per cap. (log)"),
          dep.var.caption = "Conflict type",
          dep.var.labels.include = FALSE,
          column.labels = c("Armed Group Conflict", "Civilian Conflict"),
          out = "html"
)
``` 



